name: multsample
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - biopet-extractadaptersfastqc==0.2
  - biopet-sampleconfig==0.1
  - gatk4==4.0.4.0
  - picard==2.18.7
  - cutadapt==1.16
  - fastqc==0.11.7
  - biopet-scatterregions==0.1
  - samtools==1.8
  - stringtie==1.3.4
  - htseq==0.9.1
  - r-dplyr==0.7.4
  - r-reshape2==1.4.3
  - biopet-basecounter==0.1
  - biopet-seqstat==0.1
  - star==2.6.0c

