name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopet-extractadaptersfastqc==0.2
  - biopet-sampleconfig==0.2
  - gatk4==4.0.4.0
  - picard==2.18.7
  - cutadapt==1.16
  - fastqc==0.11.7
  - biopet-scatterregions==0.2
  - samtools==1.8
  - stringtie==1.3.4
  - htseq==0.9.1
  - r-dplyr==0.7.4
  - r-reshape2==1.4.3
  - biopet-basecounter==0.1
  - biopet-seqstat==1.0.1
  - star==2.6.0c
  - biopet-validatefastq==0.1.1
  - biopet-validateannotation==0.1
  - biopet-validatevcf==0.1
  - pyyaml==3.12
  - biopet-vcfstats==1.2
  - biopet-bamstats==1.0.1
  - python <3
  - pip:
    - CPAT==1.2.4
  - gffread==0.9.9
  - gffcompare==0.10.6
  - multiqc==1.6
